
package com.yjcloud.health.vcard.webservices.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.yjcloud.health.vcard.webservices.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ErhcService", targetNamespace = "http://webservices.vcard.health.yjcloud.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ErhcService {


    /**
     * 
     * @param headerInParm
     * @param bodyInParm
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "doService")
    @WebResult(name = "MsgOutParm", targetNamespace = "")
    @RequestWrapper(localName = "doService", targetNamespace = "http://webservices.vcard.health.yjcloud.com/", className = "com.yjcloud.health.vcard.webservices.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://webservices.vcard.health.yjcloud.com/", className = "com.yjcloud.health.vcard.webservices.DoServiceResponse")
    public String doService(
            @WebParam(name = "HeaderInParm", targetNamespace = "")
                    String headerInParm,
            @WebParam(name = "BodyInParm", targetNamespace = "")
                    String bodyInParm);

}
