
package com.yjcloud.health.vcard.webservices.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ErhcServiceImplService", targetNamespace = "http://impl.webservices.vcard.health.yjcloud.com/", wsdlLocation = "http://10.1.1.246:9081/ERHC/ERHCService?wsdl")
public class ErhcServiceImplService
    extends Service
{

    private final static URL ERHCSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERHCSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ERHCSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservices.vcard.health.yjcloud.com/", "ErhcServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.1.246:9081/ERHC/ERHCService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERHCSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ERHCSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ErhcServiceImplService() {
        super(__getWsdlLocation(), ERHCSERVICEIMPLSERVICE_QNAME);
    }

    public ErhcServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERHCSERVICEIMPLSERVICE_QNAME, features);
    }

    public ErhcServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ERHCSERVICEIMPLSERVICE_QNAME);
    }

    public ErhcServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERHCSERVICEIMPLSERVICE_QNAME, features);
    }

    public ErhcServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErhcServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ErhcService
     */
    @WebEndpoint(name = "ErhcServiceImplPort")
    public ErhcService getErhcServiceImplPort() {
        return super.getPort(new QName("http://impl.webservices.vcard.health.yjcloud.com/", "ErhcServiceImplPort"), ErhcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErhcService
     */
    @WebEndpoint(name = "ErhcServiceImplPort")
    public ErhcService getErhcServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservices.vcard.health.yjcloud.com/", "ErhcServiceImplPort"), ErhcService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERHCSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ERHCSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ERHCSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
